baseURL = 'https://Allstareyes.github.io/'
locale = 'zh-cn'
title = '一个仓库'
theme = 'jijian'

[[menu.main]]
identifier = "posts"
name = "文章"
url = "/posts/"
weight = 10


[[menu.main]]
identifier = "categories"
name = "分类"
parent = "posts"
url = "/categories/"
weight = 12

[[menu.main]]
identifier = "tags"
name = "标签"
parent = "posts"
url = "/tags/"
weight = 13


[params]

ShowBreadCrumbs = true
ShowCodeCopyButtons = true
ShowPageNums = true
ShowPostNavLinks = true
ShowRssButtonInSectionTermList = true


UseHugoToc = true #显示hugo原生目录

author = "Allstareyes" #作者

defaultTheme = "auto"
disableLangToggle = false
disableScrollToTop = false
disableSpecial1stPost = false
disableThemeToggle = false
displayFullLangName = true
mainSections = ["posts", "docs"]
tocHideDelay = 2000
tocHover = false
tocHoverDelay = 200

